### ISSUE TITLE
관리가이드 부문 Glue 가이드 문서 작성 - 메뉴 생성이 필요합니다.

### ISSUE THREAD

**Issue by kt-cheon** [ablecloud-team/ablestack-docs#28]
개요
설정
사용자 및 역할 관리
프록시 설정
API 요청 감사
NFS-Ganesha 관리
플러그인
문제 해결

이상 메뉴가 Glue 가이드에 필요합니다.

**Comment by kt-cheon** [comment]
@leca777

**Comment by leca777** [comment]
사용자인터페이스
개요 -> 대시보드
설정
사용자 및 역할 관리
프록시 설정
API 요청 감사
NFS-Ganesha 관리
플러그인
문제 해결

로 메뉴 구성합니다
