### ISSUE TITLE
관리가이드 부문 Cube 가이드 문서 작성 (스토리지)

### ISSUE THREAD

**Issue by Dajeong-Park** [ablecloud-team/ablestack-docs#32]
스토리지

- [ ] partition 관리 15
- [ ] NFS mount 관리 16
- [ ] 독립 디스크 중복 관리 17
- [ ] LVM 논리 볼륨 구성 18
- [ ] thin 논리 볼륨 구성 19
- [ ] 볼륨 그룹의 물리적 드라이브 변경 20
- [ ] Virtual data optimizer 볼륨 관리 21
- [ ] Luks 비밀번호 데이터 잠금 22
- [ ] tang키를 사용하여 자동잠금 해제 구성 23

**Comment by jschoiRR** [comment]
@jschoiRR
